blank_issues_enabled: false
contact_links:
  - name: 💬 Ask A Question
    url: https://github.com/corebit-bd/headstart/discussions/new?category=q-a
    about: Ask Questions & Discuss with the Community
  - name: 💡 Feature Request Discussion
    url: https://github.com/corebit-bd/headstart/discussions/new?category=ideas
    about: Suggest An Idea for this Project (Discuss before Creating Issue)
  - name: 📚 Documentation
    url: https://github.com/corebit-bd/headstart/tree/main/documentation
    about: View Comprehensive Project Documentation
  - name: 🔒 Security Vulnerability
    url: https://github.com/corebit-bd/headstart/security/advisories/new
    about: Report a Security Vulnerability (DO NOT Create a ublic Issue)
  - name: 📖 Contributing Guide
    url: https://github.com/corebit-bd/headstart/blob/main/CONTRIBUTING.md
    about: Learn How to Contribute to this Project
